# Generated by Django 2.1.1 on 2018-09-18 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='プラント3 川北店', max_length=20, verbose_name='ガソリンスタンド名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('total', models.IntegerField(default=0, verbose_name='合計')),
                ('amount', models.FloatField(verbose_name='給油量')),
                ('refueling_date', models.DateField(default=django.utils.timezone.now, verbose_name='給油日')),
                ('trip_meter', models.FloatField(null=True, verbose_name='トリップメータの表示')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
