# Generated by Django 2.1.5 on 2019-02-13 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_auto_20180919_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20, verbose_name='ガソリンスタンド名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('confirmed_date', models.DateField(verbose_name='価格を確認した日')),
                ('acquisition_date', models.DateField(default=django.utils.timezone.now, verbose_name='取得日')),
            ],
        ),
    ]
