# Generated by Django 2.1.5 on 2019-02-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_auto_20190214_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelprice',
            options={'get_latest_by': 'acquisition_date'},
        ),
    ]
