# Generated by Django 2.1.5 on 2019-02-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_auto_20190214_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelprice',
            options={},
        ),
    ]
